### ISSUE TITLE
Resource for GA - Aggregated issues from NCSU Feedback

### ISSUE THREAD

**Issue by YufengXin** [AERPAW-Platform-Control/portal#69]
the testbed resources view is different for users with different powers - the view with the time line (available for the operators) still does not help (at this time), as the testbed resources are not scheduled through the portal at this time. testbed resources view is different for users with different powers #8

  please remove the emulab nodes from the resources; or confirm that anybody with an “Ops” role may do so. remove the emulab nodes from the resources #9

  the resources filter seems to not work (tried to filter by fixed nodes, but portable nodes still showed up) the resources filter seems to not work #10

**Comment by ericafu1122** [comment]
Commenting out the resource time line graph resolved item 8 and 10. (The resources filter specified in 10 is for the graph).
For item 9, I have unset the env related to emulab instance in aerpaw-ci.renci.org. Once portal got redeployed, emulab nodes will no longer showed.
