### ISSUE TITLE
Email enhancement for GA - Aggregated issues from NCSU Feedback

### ISSUE THREAD

**Issue by YufengXin** [AERPAW-Platform-Control/portal#70]
The mail system (which for now seems crucial for the operation of the portal), seems to be down sometimes (for hours at a time last Thursday). Mail system is sometimes down #2

And it's desired to have "Approval", "Deny", and "More information" buttons in the Email body for the PI.

**Comment by mjstealey** [comment]
Defer email embedded link / token via API actionable tasks to phase-2 as it will take some discussion prior to implementation

**Comment by mjstealey** [comment]
closing, reopen if it becomes a work item
