### ISSUE TITLE
post alpha modifications

### ISSUE THREAD

**Issue by mjstealey** [AERPAW-Platform-Control/portal#74]
Post alpha modifications per NCSU demo

- [x] add private option to projects, default project to private, do not show in any templates unless user is part of project marked as private
- [x] hide experimenter CI/CD option in all templates (operator CI/CD stays as is)
- [x] activate "join" project request for public projects that the user is not part of
- [x] enable email notifications for
    - role requests - send to all members with `manage_users` role
    - join project requests - send to `project_creator` and `project_owners` of requested project
- [ ] ~~open email request form to PI to join a project if not public~~ defer to subsequent update

**Comment by YufengXin** [comment]
One more function, if not there, PI can remove a member from the project.

**Comment by mjstealey** [comment]
> One more function, if not there, PI can remove a member from the project.

Functionality already exists at a couple of levels

- `PI` (project_creator) can add/remove project owners and project members at any time
- `Project Owners` can add/remove project members at any time
- `Project Members` cannot modify project membership at all

**Comment by mjstealey** [comment]
merged as #75 - closing
