### ISSUE TITLE
Remove the foot pane from a few pages

### ISSUE THREAD

**Issue by YufengXin** [AERPAW-Platform-Control/portal#92]
INC3817197: The bottom foot pane covers input field in the middle of the page when "zoom in" the browser. 

1. Project > Update Project Owners & Update Project Members

Let's only have the foot pane on the home page and completely remove it from all the sub-pages, maybe changing the base.html .... 

(they saw this won't be a problem when zoom out the browser, but insisted it's a 'failure')

**Comment by mjstealey** [comment]
Now using `base_no_footer.html` for any pages that use the personnel multiselect widget. 

- project update owner
- project update member
- experiment update experimenter
