### ISSUE TITLE
Email Template updates

### ISSUE THREAD

**Issue by mjstealey** [AERPAW-Platform-Control/portal#98]
Add new template option to email for Experimenter

Update emails to Experimenter based on information [here](https://docs.google.com/document/d/16sHtkXkqAa2ZnVk9MHCwatu2L2ZhGBgkHVsnqK7dk_k/edit?usp=sharing)

**Comment by YufengXin** [comment]
Clarification: These three templates are all "Ack" messages, ie., meant to be automatically generated and replied by the portal (on behalf of the operator), after a user request message being sent to the operators.
